// data.js - Demo dog breed data
const dogData = [
    {
      id: 1,
      name: "Golden Retriever",
      breedGroup: "Sporting",
      size: "Large",
      weight: "55-75 lbs",
      height: "21.5-24 inches",
      traits:"lovely",
      lifeSpan: "10-12 years",
      temperament: ["Friendly", "Intelligent", "Devoted"],
      energyLevel: "High",
      shedding: "Moderate to Heavy",
      goodWith: ["Families", "Children", "Other Dogs"],
      image: "golden-retriever.jpg",
      description: "A friendly, intelligent dog that excels as a family pet and in obedience competitions."
    },
    {
      id: 2,
      name: "French Bulldog",
      breedGroup: "Non-Sporting",
      size: "Small",
      weight: "16-28 lbs",
      traits:"lovely",
      height: "11-13 inches",
      lifeSpan: "10-12 years",
      temperament: ["Adaptable", "Playful", "Smart"],
      energyLevel: "Low to Moderate",
      shedding: "Minimal",
      goodWith: ["Families", "Apartment Living", "Seniors"],
      image: "french-bulldog.jpg",
      description: "A charming, compact companion known for its bat-like ears and even temperament."
    },
    {
      id: 3,
      name: "German Shepherd",
      breedGroup: "Herding",
      size: "Large",
      weight: "50-90 lbs",
      height: "22-26 inches",
      traits:"lovely",
      lifeSpan: "9-13 years",
      temperament: ["Courageous", "Confident", "Smart"],
      energyLevel: "High",
      shedding: "Heavy",
      goodWith: ["Families", "Active Owners", "Work Environments"],
      image: "german-shepherd.jpg",
      description: "A versatile working dog known for its intelligence and loyalty, often used in police and service roles."
    },
    {
      id: 4,
      name: "Poodle (Standard)",
      breedGroup: "Non-Sporting",
      size: "Medium to Large",
      weight: "45-70 lbs",
      height: "15+ inches",
      lifeSpan: "12-15 years",
      traits:"lovely",
      temperament: ["Active", "Proud", "Very Smart"],
      energyLevel: "High",
      shedding: "Minimal",
      goodWith: ["Families", "Allergy Sufferers", "Active Owners"],
      image: "standard-poodle.jpg",
      description: "An elegant, intelligent breed that comes in three sizes and is known for being hypoallergenic."
    },
    {
      id: 5,
      name: "Beagle",
      breedGroup: "Hound",
      size: "Small to Medium",
      weight: "20-30 lbs",
      height: "13-15 inches",
      lifeSpan: "12-15 years",
      traits:"lovely",
      temperament: ["Friendly", "Curious", "Merry"],
      energyLevel: "Moderate to High",
      shedding: "Moderate",
      goodWith: ["Families", "Children", "Other Pets"],
      image: "beagle.jpg",
      description: "A small hound dog with a great sense of smell and a lovable, gentle disposition."
    }
  ];
  
  export default dogData;